### ISSUE TITLE
emerge -avq genkernel

### ISSUE THREAD

**Issue by betogamez** [sergibarroso/gentoo_install#3]
You forgot to mention to emerge genkernel...

**Comment by sergibarroso** [comment]
Thanks for notifying this @betogamez 

I'm actually reviewing the whole document, and I'll be adding this as well.

**Comment by oz123** [comment]
While genkernel is nice, you should probably mention that nowadays gentoo ships a binary kernel package which is great for desktop and server users (it's actually using the ubuntu configuration).
