### ISSUE TITLE
ufed cannot be used anymore

### ISSUE THREAD

**Issue by dreamyphone** [sergibarroso/gentoo_install#5]
gentoo 2023 cannot use ufed anymore.
running ufed will get 

> Couldn't determine EPREFIX and PORTDIR from Portage
or 
> ERROR: insufficient parameters!

**Comment by sergibarroso** [comment]
Thanks for letting me know @dreamyphone . I will update this section of the guide ASAP :)

**Comment by sergibarroso** [comment]
Ok, after testing it, I want to confirm that `ufed` could still be used. Just that we need to install `app-portage/eix` before.

I've updated the guide anyway.

Thanks
