### ISSUE TITLE
/mnt/gentoo/boot: unknown filesystem type 'crypto_LUKS'

### ISSUE THREAD

**Issue by d3formed** [sergibarroso/gentoo_install#8]
i tried to install myself a gentoo on a virtual machine with this instruction at the step of "Mount the new filesystems", when i mount in, it tells the error.

How do i fix it?
![image](https://github.com/sergibarroso/gentoo_install/assets/98893840/6c7fd89d-69c2-4576-8ece-bdbdbb7ea02a)

**Comment by sergibarroso** [comment]
Hi @Bananduck 

Thanks for your interest in this repository.

From what I can see, you're trying to mount the whole disk, not a partition.

Please, make sure that you're following the prepare hard disk, and the following steps correctly, pay special attention to the warning:

**I will continue using NVME, but if you use a SATA disk, from now on, replace everything appearance of /dev/nvme0n1 or /dev/nvme0n1p1, for /dev/sda or dev/sda1**

If this doesn't give you enough info to solve the problem, please message me, and we can continue via email.

Thanks
